# Set to true to add reviewers to issues/PRs
addReviewers: false

# Set to true to add assignees to issues/PRs
addAssignees: true

# A list of assignees, overrides reviewers if set
assignees:
   - arminru
   - bogdandrutu
   - carlosalberto
   - jmacd
   - jsuereth
   - SergeyKanzhelev
   - tigrannajaryan
   - yurishkuro

# A number of assignees to add to the issues/PRs
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 1
