# cSpell:ignore textlintrc
# For settings, see
# https://www.streetsidesoftware.com/vscode-spell-checker/docs/configuration/
version: '0.2'
language: en-US
caseSensitive: false
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - '**/*.svg'
files:
  - '**/*.md'
patterns:
  - name: CodeBlock
    pattern: |
      /
          ^(\s*[~`]{3,})   # code-block start
          .*               # all languages and options, e.g. shell {hl_lines=[12]}
          [\s\S]*?         # content
          \1               # code-block end - cSpell:disable-next-line
      /igmx
  - name: CodeName
    pattern: |
      /
          ([~`])
          [^~`]*?
          \1
      /x
  - name: UnderscoreName
    pattern: |
      /
          ([_])
          [^_]*?
          \1
      /x
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - CodeBlock
      - CodeName
      - UnderscoreName
dictionaryDefinitions:
  - name: en-words
    path: .cspell/en-words.txt
dictionaries:
  # Local word lists
  - en-words
  # Programming languages and software terms
  - cpp
  - dotnet
  - golang
  - node
  - softwareTerms
  # Other
  - companies
words: # Valid words across all locales
  - Docsy
  - htmltest
  - jsonify
  - nvmrc
  - opentelemetrybot
  - warnf
  - warnidf
