# See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
# and https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md

# Default state for all rules
default: true

ul-style: false
line-length: false
no-duplicate-header:
  siblings_only: true
ol-prefix:
  style: ordered
no-inline-html: false
fenced-code-language: false
