{
  "default": true,
  "MD024": { "allow_different_nesting": true },
  "MD029": { "style": "ordered" },
  "ul-style": false,  # MD004
  "line-length": false,  # MD013
  "no-inline-html": false,  # MD033
  "fenced-code-language": false  # MD040
}
