# Default state for all rules
default: true

# heading-increment"
MD001: false

# ul-style
MD004: false

# line-length
MD013: false

# no-duplicate-header
MD024:
  siblings_only: true

# ol-prefix
MD029:
  style: ordered

# no-blanks-blockquote
MD028: false

# no-inline-html
MD033: false

# no-space-in-code
MD038: false

# fenced-code-language
MD040: false
