on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: Markdown Link Check
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@master
