name: 'Auto Assign Issue'
on:
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-assign@d5c3a5711d7fd917f7fbd746e9c6fc044f29009f
        with:
          CONFIG_FILE: ".github/auto_assign_issue.yml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
