name: 'Auto Assign PR'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-owner:
    runs-on: ubuntu-latest
    steps:
      - name: run
        uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          configuration-path: ".github/auto_assign_pr.yml"
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
