name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "2 22 * * 3" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@dde3047a8f219c296772c17936b9d02bb7447af5 # v0.12.0
