name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "2 22 * * 3" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@03559ef555db0eae5d85c3c6347d1530243e7aa7 # v0.13.0
