name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "2 22 * * 3" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@ad1959372f2919fcf2556d3a3d12ed5265c54209 # v0.16.0
