name: Semantic Conventions Check
on:
  push:
    tags: [ '**' ]
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/semantic-convention-check.yml
      - '**/semantic_conventions/**'

jobs:
  test-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify that semantic convention tables are up-to-date
      run: docker run --rm -v $(pwd)/semantic_conventions:/source -v $(pwd)/specification:/spec otel/semconvgen -f /source markdown -md /spec --md-check