name: "Close stale pull requests and issues"
on:
  schedule:
    - cron: "12 3 * * *" # arbitrary time not to DDOS GitHub

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write # required for marking and closing stale PRs
      issues: write # required for marking and closing stale issues
      actions: write # required for the stale action to manage (reset) its state cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR was marked stale. It will be closed in 14 days without additional activity.'
          close-pr-message: 'Closed as inactive. Feel free to reopen if this PR is still being worked on.'
          exempt-pr-labels: 'release:after-ga'
          stale-issue-message: 'This issue was marked stale due to lack of activity. It will be closed in 14 days without additional activity.'
          close-issue-message: > 
            Closed due to inactivity. We appreciate your input, and if this issue is still relevant,
            please feel free to reopen it. Thank you for your contribution!
          # applies only to pull requests
          days-before-pr-stale: 14
          days-before-pr-close: 14
          # applies only to issues (~12 months of inactivity)
          days-before-issue-stale: 365
          days-before-issue-close: 14
