name: "Close stale pull requests"
on:
  schedule:
    - cron: "12 3 * * *" # arbitrary time not to DDOS GitHub

permissions:
  contents: read

jobs:
  stale:
    permissions:
      pull-requests: write # required for marking and closing stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR was marked stale. It will be closed in 14 days without additional activity.'
          close-pr-message: 'Closed as inactive. Feel free to reopen if this PR is still being worked on.'
          exempt-pr-labels: 'release:after-ga'
          # opt out of defaults to avoid marking issues as stale
          days-before-stale: -1
          days-before-close: -1
          # overrides the above only for pull requests
          days-before-pr-stale: 14
          days-before-pr-close: 14
