name: "Close stale pull requests"
on:
  schedule:
    - cron: "12 3 * * *" # arbitrary time not to DDOS GitHub

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR was marked stale due to lack of inactivity. It will be closed in 7 days'
        close-pr-message: 'Closed as inactive'
        days-before-stale: 14
        days-before-close: 7
        debug-only: true
